# Generated by Django 4.2.14 on 2024-07-13 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='author',
            new_name='useraccount',
        ),
    ]
