# Generated by Django 4.2.14 on 2024-07-13 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_rename_author_posts_useraccount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
