# Generated by Django 4.2.14 on 2024-07-14 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_rename_posts_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['post_date']},
        ),
    ]
