# Generated by Django 4.2.14 on 2024-07-16 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-post_date']},
        ),
        migrations.RenameField(
            model_name='postcomment',
            old_name='posts',
            new_name='post',
        ),
    ]
